---
title: "Trend Analysis - Conformity Data"
params:
  inFile: NA
  out: NA
output:
  word_document:
    reference_docx: report-template.docx
---

```{r fit, include=FALSE, cache=TRUE}
out <- params$out
n_col <- 4
n_row <- ceiling(length(unique(out$out_tab$Matrix)) / n_col)
h <- 2 * n_row
```

_Report generated on **`r Sys.Date()`**_

_Input file: **`r params$inFile`**_

The trend analyses in this report are based on a logistic regression using non-conformity as dependent variable and year of analysis as independent variable, and implemented using `r R.version.string`.

## Summary table

```{r table, echo=FALSE}
summary_tab <- out$out_tab
colnames(summary_tab) <- paste0("**", colnames(summary_tab), "**")
knitr::kable(summary_tab)
```

## Detailed trend analyses

```{r, echo=FALSE, results='asis', message=FALSE, warnings=FALSE, fig.width=10, fig.height=h}
all_comp <- unique(out$out_tab$Component)
for (i in seq(all_comp)) {
  cat("### ", i, ". ", all_comp[i], "   \n\n", sep = "")
  
  id <- which(out$out_tab$Component == all_comp[i])
  comp_list <- out$out_list[id]
  
  par(mfrow = c(n_row, n_col))
  
  for (j in seq(comp_list)) {
    attach(comp_list[[j]])
  
    plot(years, apply(mx, 1, prop.table)[1,],
         ylim = c(0,1), xlab = "", ylab = "", las = 1)
    if (sum(mx) > 0) lines(years, expit(predict(fit)), col = "red")
  
    mtext(gsub(" - ", "\n", MAT), line = 1, cex = .8)
    legend("topright", sprintf("p=%s", p), bty = "n")
  }
  
  cat("   \n\n")
}
```
